//
// Created by ahmed Ibrahim on 12-Feb-25.
//

#ifndef DESIGNI_BACKEND_LANDDIVISIONBASEDONMAXIMIZECONNECTIONS_H
#define DESIGNI_BACKEND_LANDDIVISIONBASEDONMAXIMIZECONNECTIONS_H


class LandDivisionBasedOnMaximizeConnections {

};


#endif //DESIGNI_BACKEND_LANDDIVISIONBASEDONMAXIMIZECONNECTIONS_H
