//
// Created by ahmed Ibrahim on 12-Feb-25.
//

#ifndef DESIGNI_BACKEND_LANDDIVISIONBASEDONMINIMIZEACUTEANGLES_H
#define DESIGNI_BACKEND_LANDDIVISIONBASEDONMINIMIZEACUTEANGLES_H


class LandDivisionBasedOnMinimizeAcuteAngles {

};


#endif //DESIGNI_BACKEND_LANDDIVISIONBASEDONMINIMIZEACUTEANGLES_H
